language: erlang

otp_release:
  - '21.2'

env:
  EX_HOME: ${TRAVIS_BUILD_DIR}/elixir
  EX_BIN: ${EX_HOME}/bin
  ELIXIR: ${EX_BIN}/elixir
  MIX: ${EX_BIN}/mix
  EX_VSN: 1.7.1

before_script:
  - git clone https://github.com/elixir-lang/elixir.git ${EX_HOME}
  - pushd ${EX_HOME}
  - git checkout v${EX_VSN}
  - make
  - popd
  - ${ELIXIR} ${MIX} local.hex --force
  - ${ELIXIR} ${MIX} local.rebar --force

script:
  - ${ELIXIR} ${MIX} deps.get
  - MIX_ENV=test ${ELIXIR} ${MIX} deps.compile
  - ${ELIXIR} ${MIX} test
